version: '3.8'
services:
  database:
    container_name: ${PROJECT_NAME}_database
    image: mariadb:10.9.2
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_PASSWORD: "true"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: ${PROJECT_NAME}_php
    build:
      context: ./docker
    ports:
      - ${WEB_CONTAINER_PORT}:80
    volumes:
      - ./:/var/www/appointment_app
    depends_on:
      - database
  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/appointment_app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database